#!/bin/sh
# Migration 4 --> 5

# Fix kubeovn crds
fluxcd_crds=$(kubectl get crd -o name | grep '\.fluxcd\.io$')
if [ -n "$fluxcd_crds" ]; then
  kubectl annotate $fluxcd_crds meta.helm.sh/release-namespace=cozy-fluxcd meta.helm.sh/release-name=fluxcd
  kubectl label $fluxcd_crds app.kubernetes.io/managed-by=Helm
fi

# Write version to cozystack-version config
kubectl create configmap -n cozy-system cozystack-version --from-literal=version=5 --dry-run=client -o yaml | kubectl apply -f-
