include ../../hack/app-talos.mk

export SERVER = https://192.168.100.10:6443
export ENDPOINT := 135.181.169.168
export NODES_CONTROL = 192.168.100.11 192.168.100.12 192.168.100.13
export NODES_WORKERS = 
export NODE := $(NODES_CONTROL) $(NODES_WORKERS)
