include ../../hack/app-talos.mk

export SERVER = https://192.168.0.110:6443
export ENDPOINT := 192.168.0.110
export NODES_CONTROL = 192.168.0.111 192.168.0.112 192.168.0.113
export NODES_WORKERS = 
export NODE := $(NODES_CONTROL) $(NODES_WORKERS)
