{
 "title": "Deprecated APIs",
 "description": "Track whether the cluster can be upgraded to the newer Kubernetes versions",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "datasource", "query": "prometheus" },
   {
    "name": "k8s",
    "label": "Desired K8s version",
    "query": {
     "query": "label_values(apiserver_requested_deprecated_apis, removed_release)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current K8s version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum by (git_version) (kubernetes_build_info{job=\"kube-apiserver\"}))",
     "legendFormat": "{{ git_version }}"
    }
   ]
  },
  {
   "title": "Upgrade to desired version status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    ceil(\n        sum by(removed_release, resource, group, version) (\n            sum by(removed_release, resource, group, version) \n            (apiserver_requested_deprecated_apis{removed_release=\"$k8s\"}) \n            *\n            on(group,version,resource,subresource)\n            group_right() (increase(apiserver_request_total[1h]))\n        )\n    )\n) or vector(0)\n+ \nsum(\n    sum by (api_version, kind, helm_release_name, helm_release_namespace)\n    (resource_versions_compatibility{k8s_version=~\"$k8s\"})\n) or vector(0)\n> 0"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<br>\n\n#### Follow instructions to migrate from using **deprecated APIs**\n\nhttps://kubernetes.io/docs/reference/using-api/deprecation-guide/"
   }
  },
  {
   "title": "Requests to kube-apiserver (last 3 hours)",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "ceil(\n    sum by(removed_release, resource, group, version)(\n        sum by(removed_release, resource, group, version) \n        (apiserver_requested_deprecated_apis{removed_release=~\"$k8s\"}) \n        * \n        on(group,version,resource,subresource)\n        group_right() (increase(apiserver_request_total[3h]))\n    )\n) > 0"
    }
   ]
  },
  {
   "title": "Helm releases",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum by (api_version, kind, helm_release_name, helm_release_namespace) (resource_versions_compatibility{k8s_version=~\"$k8s\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}