{
 "title": "NTP",
 "description": "Dashboard for chrony or OpenNTPD.",
 "tags": [ "nodes" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_ntp_sanity, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Unsynced clocks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (node_timex_sync_status{node=~\"$node\"}==0)\nor vector(0)"
    }
   ]
  },
  {
   "title": "Insane nodes",
   "type": "singlestat",
   "description": "Aggregate NTPD health including stratum, leap flag, sane freshness, root distance being less than collector.ntp.max-distance and causality violation being less than collector.ntp.local-offset-tolerance.\n\nCausality violation is lower bound estimate of clock error done using SNTP, it's calculated as positive portion of abs(node_ntp_offset) - node_ntp_rtt / 2.",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Reference ID",
     "expr": "count (node_ntp_sanity{node=~\"$node\"}==0)\nor vector(0)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "chrony",
     "query": "SELECT \"reference_id\"  FROM (SELECT \"reference_id\", \"system_time\" FROM \"chrony\" WHERE $timeFilter)",
     "select": [
      [
       { "params": [ "stratum" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stratum 16 nodes",
   "type": "singlestat",
   "description": "The stratum indicates how many hops away from a computer with an attached reference clock we are. Such a computer is a stratum-1 computer, so the computer in the example is two hops away (i.e. foo.example.net is a stratum-2 and is synchronised from a stratum-1)",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Stratum",
     "expr": "count (node_ntp_stratum{node=~\"$node\"}==16)\nor vector(0)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "chrony",
     "query": "SELECT \"stratum\"  FROM (SELECT \"stratum\", \"system_time\" FROM \"chrony\" WHERE $timeFilter)",
     "select": [
      [
       { "params": [ "stratum" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "max by (node) (min_over_time(node_timex_sync_status{node=~\"$node\"}[$__range]))",
     "legendFormat": "Sync status"
    },
    {
     "expr": "max by (node) (min_over_time(node_ntp_sanity{node=~\"$node\"}[$__range]))",
     "legendFormat": "Sanity"
    },
    {
     "expr": "max by (node) (max_over_time(node_ntp_stratum{node=~\"$node\"}[$__range]))",
     "legendFormat": "Stratum"
    },
    {
     "expr": "max by (node) (max_over_time(node_ntp_offset_seconds:abs{node=~\"$node\"}[$__range]))",
     "legendFormat": "Offset"
    },
    {
     "expr": "max by (node) (max_over_time(node_ntp_rtt_seconds{node=~\"$node\"}[$__range]))",
     "legendFormat": "RTT"
    },
    {
     "expr": "max by (node) (max_over_time(node_ntp_root_dispersion_seconds{node=~\"$node\"}[$__range]))",
     "legendFormat": "Root dispersion"
    },
    {
     "expr": "max by (node) (max_over_time(node_ntp_root_delay_seconds{node=~\"$node\"}[$__range]))",
     "legendFormat": "Root delay"
    },
    {
     "expr": "max by (node) (node_time_seconds{node=~\"$node\"} - node_ntp_reference_timestamp_seconds{node=~\"$node\"})",
     "legendFormat": "Last click adjustment"
    }
   ]
  },
  {
   "title": "Max RTT",
   "type": "graph",
   "description": "RTT (round-trip time) from node_exporter collector to local NTPD. This value is used in sanity check as part of causality violation estimate.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Frequency",
     "expr": "max_over_time(node_ntp_rtt_seconds{node=~\"$node\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{node}}",
     "measurement": "chrony",
     "select": [
      [
       { "params": [ "frequency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max offset",
   "type": "graph",
   "description": "Offset - This is the estimated local offset to the ntp sources on the last clock update.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Last Offset",
     "expr": "(max_over_time(node_ntp_offset_seconds{node=~\"$node\"}[$__rate_interval]) > 0)\nor\n(min_over_time(node_ntp_offset_seconds{node=~\"$node\"}[$__rate_interval]) < 0)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{node}}",
     "measurement": "chrony",
     "select": [
      [
       { "params": [ "last_offset" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max root dispersion",
   "type": "graph",
   "description": "RTT (round-trip time) from node_exporter collector to local NTPD. This value is used in sanity check as part of causality violation estimate.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Frequency",
     "expr": "max_over_time(node_ntp_root_dispersion_seconds{node=~\"$node\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{node}}",
     "measurement": "chrony",
     "select": [
      [
       { "params": [ "frequency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max root delay",
   "type": "graph",
   "description": "Offset - This is the estimated local offset to the ntp sources on the last clock update.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Last Offset",
     "expr": "(max_over_time(node_ntp_root_delay_seconds{node=~\"$node\"}[$__rate_interval]) > 0)\nor\n(min_over_time(node_ntp_root_delay_seconds{node=~\"$node\"}[$__rate_interval]) < 0)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{node}}",
     "measurement": "chrony",
     "select": [
      [
       { "params": [ "last_offset" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Clock Adjustment",
   "type": "graph",
   "description": "Reference Time. This field show time when the last adjustment was made, but implementation details vary from \"local wall-clock time\" to \"Reference Time field in incoming SNTP packet\".\n\nrepresent some estimate of \"freshness\" of synchronization.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "node_time_seconds - node_ntp_reference_timestamp_seconds{node=~\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}