{
 "title": "Volumes",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kubelet_volume_stats_capacity_bytes, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Persistent Volume Usage",
   "type": "bargauge",
   "gridPos": { "h": 26, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"} / kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"})",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Persistent Volume Inodes Usage",
   "type": "bargauge",
   "gridPos": { "h": 26, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(kubelet_volume_stats_inodes_used{namespace=~\"$namespace\"} / kubelet_volume_stats_inodes{namespace=~\"$namespace\"})",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "kube-state",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Persistent Volume Status by Phase",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_persistentvolume_status_phase{phase=\"Bound\"} == 1",
       "legendFormat": "{{phase}} - {{persistentvolume}}"
      }
     ]
    },
    {
     "title": "Persistent Volume Claim Status by Phase",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_persistentvolumeclaim_status_phase{phase=\"Pending\"} == 1",
       "legendFormat": "{{phase}} - {{persistentvolumeclaim}} "
      },
      {
       "expr": "kube_persistentvolumeclaim_status_phase{phase=\"Lost\"} == 1",
       "legendFormat": "{{phase}} - {{persistentvolumeclaim}}"
      },
      {
       "expr": "kube_persistentvolumeclaim_status_phase{phase=\"Bound\"} == 1",
       "legendFormat": "{{phase}} - {{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  }
 ]
}