{
 "title": "Nginx VTS Stats",
 "description": "Show stats from nginx VTS module (direct, without exporter)",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(nginx_vts_info, namespace)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(nginx_vts_info{namespace=\"$namespace\"}, service)"
   },
   {
    "name": "host",
    "label": "HTTP Host",
    "query": "label_values(nginx_vts_server_requests_total{namespace=\"$namespace\", host!=\"*\"}, host)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(nginx_vts_server_requests_total{namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "graph",
   "description": "Requests per second grouped by response code",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_server_requests_total{namespace=\"$namespace\", service=~\"$service\", code!=\"total\", host=~\"$host\", pod=~\"$pod\"}[$__rate_interval])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_main_connections{namespace=\"$namespace\", service=~\"$service\", status=~\"active|writing|reading|waiting\", pod=~\"$pod\"}[$__rate_interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(nginx_vts_server_request_seconds{namespace=\"$namespace\", service=~\"$service\", host=~\"$host\", pod=~\"$pod\"} > 0) by (pod)",
     "legendFormat": "{{ pod }} "
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_server_bytes_total{namespace=\"$namespace\", service=~\"$service\", host=~\"$host\", pod=~\"$pod\"}[$__rate_interval])) by (direction)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Shared memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_vts_main_shm_usage_bytes{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}) by (shared)",
     "legendFormat": "{{ shared }}"
    }
   ]
  },
  { "title": "Filtered", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Requests by region",
   "type": "graph",
   "description": "Requests per second grouped by response code",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(label_replace(nginx_vts_filter_requests_total{namespace=\"$namespace\", service=~\"$service\", code!=\"total\", filter=~\"region::.*\", filter_name=~\"$host\", pod=~\"$pod\"}[$__rate_interval], \"region\", \"$1\", \"filter\", \"region::(.*)\"))) by (region)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Throughput by region",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(label_replace(nginx_vts_filter_bytes_total{namespace=\"$namespace\", service=~\"$service\", code!=\"total\", filter=~\"region::.*\", filter_name=~\"$host\", pod=~\"$pod\"}[$__rate_interval], \"region\", \"$1\", \"filter\", \"region::(.*)\"))) by (region)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Requests by host",
   "type": "graph",
   "description": "Requests per second grouped by response code",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_server_requests_total{namespace=\"$namespace\", service=~\"$service\", host=~\"$host\", host!=\"*\", pod=~\"$pod\"}[$__rate_interval]) > 0) by (host)",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Throughput by host",
   "type": "graph",
   "description": "Requests per second grouped by response code",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_server_bytes_total{namespace=\"$namespace\", service=~\"$service\", host=~\"$host\", pod=~\"$pod\"}[$__rate_interval])) by (host)",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Requests by URL",
   "type": "graph",
   "description": "Requests per second grouped by response code",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_filter_requests_total{namespace=\"$namespace\", service=~\"$service\", code!=\"total\", filter=~\"url::$host\", pod=~\"$pod\"}[$__rate_interval])) by (filter_name)",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Throughput by URL",
   "type": "graph",
   "description": "Requests per second grouped by response code",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_filter_bytes_total{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\", filter=~\"url::$host\"}[$__rate_interval])) by (filter_name)",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  { "title": "Upstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Upstream requests",
   "type": "graph",
   "description": "This one is providing aggregated error codes, but it's still possible to graph these per upstream.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_upstream_requests_total{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\", code!=\"total\"}[$__rate_interval])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Upstream throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_upstream_bytes_total{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}[$__rate_interval])) by (direction)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Upstream response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(nginx_vts_upstream_response_seconds{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"} > 0) by (backend)",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Cache events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_vts_server_cache_total{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\", host=~\"$host\"}[$__rate_interval])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Cache throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_cache_bytes_total{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}[$__rate_interval])) by (direction)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Cache usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(sum(nginx_vts_cache_usage_bytes{namespace=\"$namespace\", service=~\"$service\", cache_size=\"max\", pod=~\"$pod\"}) by (pod))",
     "legendFormat": "max"
    },
    {
     "expr": "sum(nginx_vts_cache_usage_bytes{namespace=\"$namespace\", service=~\"$service\", cache_size=\"used\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Cache Fitered",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true
  },
  {
   "title": "Cache HIT by region",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(label_replace(nginx_vts_filter_cache_total{namespace=\"$namespace\", service=~\"$service\", code!=\"total\", filter=~\"region::.*\", filter_name=~\"$host\", pod=~\"$pod\", status=\"hit\"}[$__rate_interval], \"region\", \"$1\", \"filter\", \"region::(.*)\"))) by (region)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache HIT by host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(label_replace(nginx_vts_filter_cache_total{namespace=\"$namespace\", service=~\"$service\", code!=\"total\", filter=~\"region::.*\", filter_name=~\"$host\", pod=~\"$pod\", status=\"hit\"}[$__rate_interval], \"region\", \"$1\", \"filter\", \"region::(.*)\"))) by (filter_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache MISS by region",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(label_replace(nginx_vts_filter_cache_total{namespace=\"$namespace\", service=~\"$service\", code!=\"total\", filter=~\"region::.*\", filter_name=~\"$host\", pod=~\"$pod\", status=\"miss\"}[$__rate_interval], \"region\", \"$1\", \"filter\", \"region::(.*)\"))) by (region)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache MISS by host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(label_replace(nginx_vts_filter_cache_total{namespace=\"$namespace\", service=~\"$service\", code!=\"total\", filter=~\"region::.*\", filter_name=~\"$host\", pod=~\"$pod\", status=\"miss\"}[$__rate_interval], \"region\", \"$1\", \"filter\", \"region::(.*)\"))) by (filter_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache STALE by region",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(label_replace(nginx_vts_filter_cache_total{namespace=\"$namespace\", service=~\"$service\", code!=\"total\", filter=~\"region::.*\", filter_name=~\"$host\", pod=~\"$pod\", status=\"stale\"}[$__rate_interval], \"region\", \"$1\", \"filter\", \"region::(.*)\"))) by (region)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache STALE by host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(label_replace(nginx_vts_filter_cache_total{namespace=\"$namespace\", service=~\"$service\", code!=\"total\", filter=~\"region::.*\", filter_name=~\"$host\", pod=~\"$pod\", status=\"stale\"}[$__rate_interval], \"region\", \"$1\", \"filter\", \"region::(.*)\"))) by (filter_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache HIT by URL",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_vts_filter_cache_total{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\", filter=~\"url::$host\", status=\"hit\"}[$__rate_interval])) by (filter_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache MISS by URL",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_vts_filter_cache_total{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\", filter=~\"url::$host\", status=\"miss\"}[$__rate_interval])) by (filter_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache STALE by URL",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_vts_filter_cache_total{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\", filter=~\"url::$host\", status=\"stale\"}[$__rate_interval])) by (filter_name)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}